### ISSUE TITLE
Wallpaper Problem

### ISSUE THREAD

**Issue by ripsivis** [cyberos/cyber-workspace#13]
Starting Cyber Desktop session with LightDM gives blank unchangeable white wallpaper. GDM doesn't have that issue.

Edit: SDDM and LXDM also have that issue. Starting GNOME session for once under these display managers (except GDM) fixes the issue.

Currently running under VMware Workstation with hardened kernel and up-to-date packages.

**Comment by itsvic-dev** [comment]
a perfect solution would be to let the session know that the settings daemon is ready and to continue initializing (with DBus preferably)
