### ISSUE TITLE
Add a desktop daemon.

### ISSUE THREAD

**Issue by itsvic-dev** [cyberos/cyber-workspace#2]
One thing that I feel like is missing from `cyber-workspace` is a desktop daemon. Now, `xfdesktop` will do the job just fine, but it's not really a great long-term solution.

I have a "working" concept, though one of my issues is the fact that the desktop daemon shows up in the dock and, and the controls show up on the status bar, while this behavior doesn't happen with `xfdesktop`.
![image](https://user-images.githubusercontent.com/17727163/101661442-919d6600-3a48-11eb-8542-dd3789d0c3f3.png)
![image](https://user-images.githubusercontent.com/17727163/101661492-9f52eb80-3a48-11eb-90de-d71fae3fedef.png)
![image](https://user-images.githubusercontent.com/17727163/101661504-a548cc80-3a48-11eb-8474-88afccfdbb26.png)

I uploaded the work-in-progress code [to my fork](https://github.com/omaemae/cyber-workspace) and can be built and ran like so:
```sh
mkdir build
cd build
cmake ..
make
./desktop-daemon/cyber-desktop-daemon
```

To me, it seems like the status bar isn't respecting the `Qt.FramelessWindowHint` flag when app is full-screened. 

I have found no way of hiding the daemon from the Dock without modifying the Dock itself (which I haven't tried).

@rekols, could you help me out in trying to get this working?

**Comment by reionwong** [comment]
I've met this problem, This is a solution:

https://github.com/cyberos/cyber-statusbar/blob/e2d6e7e1c453d9f8c1020f386901f64c335e2acb/src/mainwindow.cpp#L33

**Comment by reionwong** [comment]
I've solved it. You can try it : https://github.com/omaemae/cyber-workspace/pull/2    :)
