### ISSUE TITLE
About Wallpaper

### ISSUE THREAD

**Issue by reionwong** [cyberos/cyber-workspace#3]
I think we should find some beautiful wallpaper in Unsplash or Pexels to build into our workspace project, then choose a wallpaper as the default wallpaper.

@omaemae

**Comment by itsvic-dev** [comment]
We can do that, though I'm not very sure about licensing.

**Comment by reionwong** [comment]
https://unsplash.com/license

```
License
Unsplash photos are made to be used freely. Our license reflects that.

All photos can be downloaded and used for free
Commercial and non-commercial purposes
No permission needed (though attribution is appreciated!)
What is not permitted 👎
Photos cannot be sold without significant modification.
Compiling photos from Unsplash to replicate a similar or competing service.
```

**Comment by reionwong** [comment]
We can use it on CyberOS

**Comment by itsvic-dev** [comment]
Added some wallpapers from Unsplash, superseding the old default wallpapers.

Default:
![image](https://user-images.githubusercontent.com/17727163/102226547-cd24ae00-3ee8-11eb-9ef8-85bfc952bdc3.png)
