### ISSUE TITLE
[Settings daemon] Incorrectly reporting battery as present on computers without a battery.

### ISSUE THREAD

**Issue by itsvic-dev** [cyberos/cyber-workspace#4]
The settings daemon incorrectly reports a battery present on computers without a battery:
![image](https://user-images.githubusercontent.com/17727163/102392243-1bb07600-3fd7-11eb-8b1f-dba834759156.png)
(screenshot of Cyber running on my VPS over VNC)

Any ideas? @rekols

**Comment by reionwong** [comment]
It should show no battery found.

**Comment by itsvic-dev** [comment]
Unable to check right now, will check later.
