### ISSUE TITLE
Fixed font not set in QFontDatabase

### ISSUE THREAD

**Issue by itsvic-dev** [cyberos/cyber-workspace#6]
At least I assume that's what's happening.
![image](https://user-images.githubusercontent.com/17727163/102562312-19cddc00-40d7-11eb-82ef-9ca367900115.png)

@rekols

**Comment by reionwong** [comment]
We have a Qt plugin, when you change the font, the qt plugin will receive a message here: https://github.com/cyberos/cyber-qt-plugins/blob/main/platformtheme/platformtheme.cpp#L148

But it is not valid for QML programs.

**Comment by itsvic-dev** [comment]
For now I fixed the terminal by swapping out the QFontDatabase with DBus.
