### ISSUE TITLE
[Settings Daemon] Detect a present backlight

### ISSUE THREAD

**Issue by itsvic-dev** [cyberos/cyber-workspace#7]
Do we have any way of detecting if a backlight is present or not? Would be really useful for hiding the brightness controls, or for creating an artificial brightness dim.

**Comment by reionwong** [comment]
I do not understand, Screen backlight?

**Comment by itsvic-dev** [comment]
Correct.

**Comment by itsvic-dev** [comment]
https://github.com/cyberos/cyber-workspace/commit/f1237feda98af998b2cb7d6698b1eb644088f991
