### ISSUE TITLE
[Desktop daemon] Multi-monitor support

### ISSUE THREAD

**Issue by itsvic-dev** [cyberos/cyber-workspace#9]
Currently, the desktop daemon has no support for multi-monitor arrangements:
![image](https://user-images.githubusercontent.com/17727163/108058147-e1ee0100-7053-11eb-998c-2fef507fa8c8.png)

It'd be nice if it could extend/duplicate onto other displays.

**Comment by itsvic-dev** [comment]
Very early work-in-progress.

![image](https://user-images.githubusercontent.com/17727163/108927350-69350900-7640-11eb-867d-812792f1280b.png)
![image](https://user-images.githubusercontent.com/17727163/108927371-73ef9e00-7640-11eb-8ae1-b587d3afccf1.png)

**Comment by itsvic-dev** [comment]
After a bit more code, it works. 
![image](https://user-images.githubusercontent.com/17727163/108928071-dbf2b400-7641-11eb-8bec-942ebcffcb6f.png)

**Comment by reionwong** [comment]
GOOD JOB

**Comment by itsvic-dev** [comment]
> GOOD JOB

THANK YOU, please turn off caps-lock
